Gedis with ZDB backend #24
threefoldtech/digitalmeX pull request #26
Opened 2019-03-03 16:26 UTC by BolaNasr

# How to run Notary 
## in kosmos run the following: 
```python

zdb_cl = j.clients.zdb.start_test_instance()
zdb_cl = zdb_cl.namespace_new("notary_namespace", secret="1234")
bcdb = j.data.bcdb.new(zdbclient=zdb_cl, name="notary_bcdb")
bcdb.models_add("/sandbox/code/github/threefoldtech/digitalmeX/packages/notary/models")
server = j.servers.gedis.configure(host="0.0.0.0", port=8888)
server.actor_add('/sandbox/code/github/threefoldtech/digitalmeX/packages/notary/actors/notary_actor.py')
server.models_add(models=bcdb.models.values())
server.start()                                          
```
## using Tmux
```
cd /sandbox/code/github/threefoldtech/digitalmeX/packages/notary

moonc . &&lapis server
```

# How to use it

## to register
```
curl -d '{"robot_id":"123", "key":"test", "content":"Notary", "content_signature":"Notary_test"}' -H "Content-Type: application/json" -X POST http://localhost:8080/register
```
## to get 
```
http://localhost:8080/get?key="test"
```

## to delete 
```
http://localhost:8080/delete?robot_id="123"&key="test"&content_signature="Notary_test"
```

2019-03-03 16:28 UTC, BolaNasr commented
in progress : zdb builder

2019-03-04 07:29 UTC, zaibon commented
`zdb_cl = j.clients.zdb.start_test_instance()`
This cannot be the way to start a bcdb server, it clearly state this is a test instance.

2019-03-04 07:55 UTC, zaibon requested changes
Added some comments. Some changes are required for the code to be inline with https://github.com/threefoldtech/home/issues/135#issuecomment-468336892

2019-03-04 07:55 UTC, zaibon commented on packages/notary/actors/notary_actor.py
> +        zdb_cl = j.clients.zdb.start_test_instance()
You should not start bcdb every time you do need to get an client instance to it.
BCDB should be started when gedis starts, and the you just need to have one client instance to be used here in the gedis handlers. 
Same remark for the line 18, you should not always add the models again.

2019-03-04 07:55 UTC, zaibon commented on packages/notary/actors/notary_actor.py
> +        bcdb = self.bcdb_get()
Here we need to verify the signature before saving the content.
Then the return value should also be the blak2b hash of the content.

2019-03-04 07:55 UTC, zaibon commented on packages/notary/actors/notary_actor.py
> +    def delete(self, threebot_id, key, content_signature, schema_out):
We do no need a delete method after all, see comments: https://github.com/threefoldtech/home/issues/135#issuecomment-468336892

2019-03-04 07:55 UTC, zaibon commented on packages/notary/actors/notary_actor.py
> +        out.message = "this key doesn't exist"
This should return an error not just a message. What is the proper way to return error to the client in gedis ?
Raise an exception ?

2019-03-04 22:15 UTC, LeeSmet requested changes
see comment on the verification

also, it seems like the key is currently the hash of the content. However this means that we need to include a timestamp in the encrypted content to ensure a unique key for things like e.g. a repeated reservation. I think it might be better to automatically set a timestamp to the time the content was uploaded in the notary, and then generate the key by hashing the content and all other data, e.g. blake2b(threebot_id|content|signature|timestamp).

2019-03-04 22:15 UTC, LeeSmet commented on packages/notary/actors/notary_actor.py
> +    verify_key.verify(signature)
Does verification not require both the signature and the content?

2019-03-05 07:25 UTC, zaibon commented on packages/notary/actors/notary_actor.py
> +    verify_key.verify(signature)
indeed, my mistake. I'll fix. thx

2019-03-05 07:44 UTC, zaibon commented
@LeeSmet you are write, but the timestamp is already part of what you get into the 'content' encrypted message, see https://github.com/threefoldtech/jumpscaleX/pull/216/files#diff-4843e48e342f9ae8268c7242870067f9R55

I don't think we can set the timestamp in the notary cause then we cannot verify the signature since we would change the content of the reservation.

Now this brings something else, It seems we start to have pretty much the same schema spread over different location:
- In the tfchain client for the reservation itself: https://github.com/threefoldtech/jumpscaleX/blob/cd2761e8225cdfa3c9f956a0ec6326dd7d6ab256/Jumpscale/clients/blockchain/tfchain/TFChainReservation.py#L4-L11
- In the notary to save the reservation into bcdb: https://github.com/threefoldtech/digitalmeX/blob/0e44dcd78ce78c071722e1f388f9d31f21a363fd/packages/notary/models/threefold_grid_notary_reservation.toml

These schema are somehow a bit different while still representing the same thing. Maybe we should have a central location where we store all these schema and re-use as much as possible during all the flow of reservation.

2019-03-05 08:00 UTC, LeeSmet commented
I know the timestamp is currently part of the content, my point was if it is useful to have it there? If we don't actually do anything with the timestamp (which I don't think we do), then the only reason for the timestamp to be in the content would be for it to be part of the signature (after encryption ofcourse), which gives it a proof of integrity (i.e. it can't be tampered with by the notary). But on the other hand, it feels like we just put some useless data in the content right now to ensure a unique hash.

Regardless, I still think the key hash should at least also include the threebot_id, which we know must be authentic because otherwise the signature verification would fail.

2019-03-05 08:18 UTC, zaibon commented
> I still think the key hash should at least also include the threebot_id

This is already the case, check the schema that is used to create the encrypted content:
https://github.com/threefoldtech/jumpscaleX/blob/cd2761e8225cdfa3c9f956a0ec6326dd7d6ab256/Jumpscale/clients/blockchain/tfchain/TFChainReservation.py#L4-L11

2019-03-05 08:38 UTC, LeeSmet commented
yes indeed it is part of the encrypted content, but I wonder why it is part of that, since we also need it as part of the data we upload so the notary can verify the signature. So it seems we unnecessarily duplicate some data

2019-03-05 08:44 UTC, zaibon commented
But this is what we already discussed before.
The content must contain both timestamp and threebot id to make it unique enough so user can make different reservations. 
Also I want to have these information store in the blockchain for tractability.

We indeed send the threebot id also in clear to the notary, but there is no way around that since we need it to verify the signature.

The notary is not supposed to do anything with the data, it just receive it, verify the signature and store it as is. There should be as little to no logic in the notary.

2019-03-05 08:50 UTC, LeeSmet commented
> The content must contain both timestamp and threebot id to make it unique enough so user can make different reservations.

Indeed, reason for this being the key needs to be different. So if instead of only the content we hash both the content AND the (plaintext) 3bot id we also get a unique key without duplicating the id within the encrypted content. As for storage in the blockchain, we are going to store the key bytes, with which you will be able to get the notary data, which then includes the threebot id, content, and content signature, and you can use those 3 pieces of information to verify that everything is correct. so including the 3bot id in the encrypted content does not change anything here (after all you can't decrypt the content anyway)

2019-03-05 08:57 UTC, zaibon commented
Ok that is indeed right that the notary will give you the threebot_id when you get the encrypted reservation. So I guess you're right and that can work like that.

2019-03-11 13:17 UTC, LeeSmet commented
After giving this some more though over the weekend, it seems the signature is also useless for us. All benefits we get from a signature are already implied because we use Curve25519 for key derivation, which operates on both parties keypairs at once. Really the only reason for the signature is that it allows the notary to verify that the data has been created by the 3bot defined by the threebot_id field. But even then this does not necessarily guarantee that the data can be decrypted. Thoughts @zaibon ?

2019-03-12 10:23 UTC, merged